apiVersion: v1
kind: Template
labels:
  scheduledjobs-cleanup: template
metadata:
  annotations:
    description: Create a cleanup scheduledjobs to remove scheduledjobs history in
      a project
    tags: "kermit,kermit-tooling"
  creationTimestamp: null
  name: scheduledjobs-cleanup
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: scheduledjobs-cleanup
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: system:scheduledjobs-cleanup
  roleRef:
    name: kermit-user
  subjects:
  - kind: SystemUser
    name: system:serviceaccounts:${PROJECT_NAME}:scheduledjobs-cleanup
    namespace: ${PROJECT_NAME}
  userNames:
  - system:serviceaccount:${PROJECT_NAME}:scheduledjobs-cleanup
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Resulting Docker Image after the build of my scheduled job.
    labels:
      app: scheduledjobs-cleanup
    name: scheduledjobs-cleanup
  spec:
    tags:
    - tag: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: scheduledjobs-cleanup-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: scheduledjobs-cleanup:latest
    runPolicy: Serial
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    spec: null
    strategy:
      dockerStrategy:
        env:
        - name: USER_DURATION
          value: ${USER_DURATION}
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: batch/v2alpha1
  kind: ScheduledJob
  metadata:
    name: scheduledjobs-cleanup
  spec:
    jobTemplate:
      spec:
        template:
          spec:
            activeDeadlineSeconds: 600
            containers:
            - image: 172.30.220.103:5000/${PROJECT_NAME}/scheduledjobs-cleanup:latest
              name: scheduledjobs-cleanup
            restartPolicy: OnFailure
            serviceAccountName: scheduledjobs-cleanup
    schedule: ${SCHEDULE_VALUE}
parameters:
- description: Project Name used to create the RoleBindings
  name: PROJECT_NAME
  required: true
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/orangekmt/openshift-scheduled-jobs-cleanup.git
- description: Value to set for the schedule (cron format)
  displayName: ' Value for the Schedule'
  name: SCHEDULE_VALUE
  value: '*/1 * * * ?'
- description: Duration set by user in SECONDS. Jobs older than this duration will be deleted.
  name: USER_DURATION
  value: "600"
